// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6zN7ztyKFqRyOwZE8-yRyjPGiT_l5LPM',
    appId: '1:461558279479:web:27b1159cd455cb371dbeb2',
    messagingSenderId: '461558279479',
    projectId: 'flutter-chat-app-863ac',
    authDomain: 'flutter-chat-app-863ac.firebaseapp.com',
    storageBucket: 'flutter-chat-app-863ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgD9yyXA3sFiMvAURZayF7Q4KWutD4LSo',
    appId: '1:461558279479:android:d29b98d2ec7ee1be1dbeb2',
    messagingSenderId: '461558279479',
    projectId: 'flutter-chat-app-863ac',
    storageBucket: 'flutter-chat-app-863ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICOAccWdvT8CUuTGoqLRGMWyixAphr6w',
    appId: '1:461558279479:ios:60f3abd87cd1eb6d1dbeb2',
    messagingSenderId: '461558279479',
    projectId: 'flutter-chat-app-863ac',
    storageBucket: 'flutter-chat-app-863ac.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICOAccWdvT8CUuTGoqLRGMWyixAphr6w',
    appId: '1:461558279479:ios:aae9dadb462e05d31dbeb2',
    messagingSenderId: '461558279479',
    projectId: 'flutter-chat-app-863ac',
    storageBucket: 'flutter-chat-app-863ac.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
